// MCQ Questions Database - 150 Questions total
export interface MCQQuestion {
  id: number;
  question: string;
  options: string[];
  correct: number;
  category: string;
}

export interface QuizAttempt {
  userId: string;
  userEmail: string;
  attemptNumber: number;
  selectedQuestions: number[]; // IDs of 15 questions
  answers: number[]; // User's answers
  score: number;
  passed: boolean;
  timestamp: Date;
}

export const MCQ_QUESTIONS: MCQQuestion[] = [
  {
    "id": 1,
    "question": "What is the primary function of an aircraft's ailerons?",
    "options": [
      "To control pitch",
      "To control yaw",
      "To control roll",
      "To control thrust"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 2,
    "question": "Which of the four fundamental forces of flight opposes the forward motion of the aircraft?",
    "options": [
      "Lift",
      "Thrust",
      "Weight",
      "Drag"
    ],
    "correct": 3,
    "category": "Aerodynamics"
  },
  {
    "id": 3,
    "question": "According to Bernoulli's principle, an increase in fluid speed results in a decrease in what?",
    "options": [
      "Density",
      "Temperature",
      "Pressure",
      "Volume"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 4,
    "question": "The angle between the chord line of an airfoil and the relative wind is called the:",
    "options": [
      "Angle of incidence",
      "Angle of sweep",
      "Angle of attack",
      "Dihedral angle"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 5,
    "question": "What is 'Stall' in the context of flight?",
    "options": [
      "When the engine fails",
      "When the aircraft flies too fast",
      "When the wing exceeds its critical angle of attack",
      "When the landing gear is deployed"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 6,
    "question": "The center of gravity (CG) of an aircraft is the point where:",
    "options": [
      "Lift is generated",
      "Thrust is applied",
      "All weight is considered to be concentrated",
      "Drag is minimum"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 7,
    "question": "Which axis of an aircraft is controlled by the elevator?",
    "options": [
      "Lateral (Pitch)",
      "Longitudinal (Roll)",
      "Vertical (Yaw)",
      "Thrust"
    ],
    "correct": 0,
    "category": "Aerodynamics"
  },
  {
    "id": 8,
    "question": "What is the purpose of wing flaps?",
    "options": [
      "To increase speed",
      "To decrease drag",
      "To increase lift and drag for slower flight",
      "To stabilize the aircraft in cruise"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 9,
    "question": "The ratio of the lift generated by a wing to the drag it creates is known as the:",
    "options": [
      "Aspect Ratio",
      "Lift-to-Drag Ratio",
      "Taper Ratio",
      "Thrust Ratio"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 10,
    "question": "What is the name of the imaginary line connecting the leading and trailing edges of an airfoil?",
    "options": [
      "Mean camber line",
      "Chord line",
      "Stagnation line",
      "Center line"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 11,
    "question": "Which flight control surface primarily controls the yawing motion?",
    "options": [
      "Ailerons",
      "Elevator",
      "Rudder",
      "Spoilers"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 12,
    "question": "The main contributor to skin friction drag is the fluid's:",
    "options": [
      "Viscosity",
      "Density",
      "Velocity",
      "Pressure"
    ],
    "correct": 0,
    "category": "Aerodynamics"
  },
  {
    "id": 13,
    "question": "What is dynamic pressure (q)?",
    "options": [
      "P_0 - P_∞",
      "½ρV²",
      "ρV",
      "P_∞"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 14,
    "question": "What is the altitude where an aircraft's performance is zero (no excess power)?",
    "options": [
      "Absolute Ceiling",
      "Service Ceiling",
      "Cruise Altitude",
      "Takeoff Altitude"
    ],
    "correct": 0,
    "category": "Aerodynamics"
  },
  {
    "id": 15,
    "question": "What causes induced drag?",
    "options": [
      "Friction between air and surface",
      "The creation of wingtip vortices",
      "Interference between components",
      "Air compressibility effects"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 16,
    "question": "The 'standard atmosphere' model is used primarily for what?",
    "options": [
      "Predicting weather patterns",
      "Calibrating flight instruments and comparing performance",
      "Calculating fuel consumption",
      "Determining engine life"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 17,
    "question": "What term describes the condition where the airflow remains smooth and attached to the surface?",
    "options": [
      "Turbulent flow",
      "Separated flow",
      "Laminar flow",
      "Transonic flow"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 18,
    "question": "What is the typical shape of the lift curve slope (C_l vs α) for a subsonic airfoil?",
    "options": [
      "Parabolic",
      "Linear",
      "Exponential",
      "Hyperbolic"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 19,
    "question": "What does the term 'Mach 1' represent?",
    "options": [
      "The speed of sound",
      "The speed of light",
      "The speed of the aircraft's engine fan",
      "The maximum speed of the aircraft"
    ],
    "correct": 0,
    "category": "Aerodynamics"
  },
  {
    "id": 20,
    "question": "The angle of attack for zero lift is usually:",
    "options": [
      "Zero degrees",
      "Positive (above 0)",
      "Negative (below 0)",
      "90 degrees"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 21,
    "question": "The downward deflection of air by the wing is often referred to as:",
    "options": [
      "Downwash",
      "Upwash",
      "Flap deflection",
      "Vortex shedding"
    ],
    "correct": 0,
    "category": "Aerodynamics"
  },
  {
    "id": 22,
    "question": "If the density of air decreases, what happens to the lift generated by a wing at a constant angle of attack and true airspeed?",
    "options": [
      "Increases",
      "Decreases",
      "Remains the same",
      "Becomes zero"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 23,
    "question": "What is the function of the horizontal stabilizer?",
    "options": [
      "To control roll",
      "To control pitch",
      "To control yaw",
      "To provide thrust"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 24,
    "question": "The primary purpose of a 'spoiler' on the wing is to:",
    "options": [
      "Increase lift",
      "Decrease drag",
      "Decrease lift and increase drag",
      "Increase thrust"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 25,
    "question": "In steady, level flight, which two forces are in equilibrium?",
    "options": [
      "Lift & Thrust",
      "Thrust & Drag",
      "Lift & Weight, and Thrust & Drag",
      "Weight & Drag"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 26,
    "question": "What is the main component that compresses air in a jet engine?",
    "options": [
      "Turbine",
      "Combustor",
      "Compressor",
      "Nozzle"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 27,
    "question": "In a turbofan engine, what is the term for the air that bypasses the core engine?",
    "options": [
      "Primary air",
      "Core flow",
      "Bypass flow",
      "Exhaust flow"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 28,
    "question": "What is the chemical process that occurs in the combustion chamber of a jet engine?",
    "options": [
      "Oxidation",
      "Vaporization",
      "Combustion",
      "Reduction"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 29,
    "question": "What is the purpose of the turbine in a gas turbine engine?",
    "options": [
      "To convert kinetic energy of the hot gas into rotational power",
      "To compress the air",
      "To mix fuel and air",
      "To cool the exhaust gas"
    ],
    "correct": 0,
    "category": "Propulsion"
  },
  {
    "id": 30,
    "question": "Thrust is a reaction force described by which of Newton's Laws of Motion?",
    "options": [
      "First Law",
      "Second Law",
      "Third Law",
      "Law of Gravity"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 31,
    "question": "Which type of engine is most commonly used on commercial passenger aircraft?",
    "options": [
      "Piston Engine",
      "Ramjet",
      "Turbojet",
      "Turbofan"
    ],
    "correct": 3,
    "category": "Propulsion"
  },
  {
    "id": 32,
    "question": "What is the section of a jet engine where the air velocity is increased to create thrust?",
    "options": [
      "Compressor",
      "Combustor",
      "Turbine",
      "Nozzle"
    ],
    "correct": 3,
    "category": "Propulsion"
  },
  {
    "id": 33,
    "question": "What is the term for the maximum rotational speed of a propeller or fan?",
    "options": [
      "RPM",
      "Thrust limit",
      "Pitch angle",
      "Mach number"
    ],
    "correct": 0,
    "category": "Propulsion"
  },
  {
    "id": 34,
    "question": "How does an afterburner increase the thrust of a turbojet engine?",
    "options": [
      "By adding more compression stages",
      "By re-igniting fuel in the exhaust nozzle",
      "By increasing the fan diameter",
      "By decreasing the bypass ratio"
    ],
    "correct": 1,
    "category": "Propulsion"
  },
  {
    "id": 35,
    "question": "The main energy source for aircraft propulsion is derived from:",
    "options": [
      "Nuclear power",
      "Solar energy",
      "Chemical energy (fuel)",
      "Gravitational potential energy"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 36,
    "question": "What is the principle behind a rocket engine's operation in space?",
    "options": [
      "It pushes against the surrounding vacuum",
      "It uses the oxygen in the air",
      "It expels mass at high velocity (Newton's Third Law)",
      "It uses magnetic levitation"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 37,
    "question": "What is the core difference between a turboprop and a turbofan engine?",
    "options": [
      "Turboprops use a propeller to generate thrust, while turbofans use a ducted fan.",
      "Turboprops are only used on large aircraft.",
      "Turboprops have no turbine.",
      "Turbofans do not use a compressor."
    ],
    "correct": 0,
    "category": "Propulsion"
  },
  {
    "id": 38,
    "question": "The main body of an aircraft that holds the crew, passengers, and cargo is called the:",
    "options": [
      "Wing",
      "Empennage",
      "Fuselage",
      "Nacelle"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 39,
    "question": "What is the horizontal component of the empennage called?",
    "options": [
      "Vertical Stabilizer",
      "Horizontal Stabilizer",
      "Rudder",
      "Aileron"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 40,
    "question": "What is the purpose of the landing gear system?",
    "options": [
      "To provide structural integrity to the wings",
      "To support the aircraft during ground operations",
      "To control the yaw axis",
      "To generate lift"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 41,
    "question": "A structure primarily designed to carry bending loads is often called a:",
    "options": [
      "Strut",
      "Beam",
      "Tie-rod",
      "Rivet"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 42,
    "question": "What does the acronym 'HUD' stand for in avionics?",
    "options": [
      "High-Use Display",
      "Head-Up Display",
      "Highly Unified Device",
      "Hovering Utility Data"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 43,
    "question": "The pressure inside a pressurized aircraft cabin at cruise altitude is typically equivalent to the atmospheric pressure at what approximate altitude?",
    "options": [
      "Sea level",
      "5,000 to 8,000 ft",
      "35,000 ft",
      "50,000 ft"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 44,
    "question": "Which system provides electrical power for the aircraft's instruments, lights, and radios?",
    "options": [
      "Hydraulic System",
      "Pneumatic System",
      "Electrical System",
      "Fuel System"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 45,
    "question": "What is the primary function of the flight control 'trim' system?",
    "options": [
      "To increase maximum speed",
      "To neutralize control pressures for a desired flight condition",
      "To decrease drag",
      "To automatically land the aircraft"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 46,
    "question": "What is the common term for the rear section of an aircraft, including the tail and control surfaces?",
    "options": [
      "Cockpit",
      "Wing box",
      "Empennage",
      "Belly fairing"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 47,
    "question": "Which force is typically the largest structural load an aircraft experiences during landing?",
    "options": [
      "Thrust",
      "Drag",
      "Lift",
      "Weight and G-forces"
    ],
    "correct": 3,
    "category": "Structure"
  },
  {
    "id": 48,
    "question": "What material is currently the most widely used for constructing commercial aircraft primary structure?",
    "options": [
      "Wood",
      "Steel",
      "Aluminum Alloys",
      "Titanium"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 49,
    "question": "The structure that attaches the wing to the fuselage is often called the:",
    "options": [
      "Pylon",
      "Wing spar",
      "Wing root",
      "Flap track"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 50,
    "question": "What is the role of the 'avionics' systems?",
    "options": [
      "Provide power to the engine",
      "Control the flight control surfaces directly",
      "Electronic systems for communication, navigation, and display",
      "Hold the fuel"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 51,
    "question": "What is the definition of true airspeed (TAS)?",
    "options": [
      "Indicated airspeed corrected for density altitude",
      "The speed relative to the ground",
      "Calibrated airspeed",
      "The speed relative to the wind"
    ],
    "correct": 0,
    "category": "Flight Mechanics"
  },
  {
    "id": 52,
    "question": "During a steady turn, what force provides the necessary centripetal acceleration?",
    "options": [
      "Thrust",
      "Rudder deflection",
      "Horizontal component of lift",
      "Vertical component of lift"
    ],
    "correct": 2,
    "category": "Flight Mechanics"
  },
  {
    "id": 53,
    "question": "What is 'G-force'?",
    "options": [
      "The force generated by the engine",
      "A measure of acceleration in multiples of the acceleration due to gravity",
      "The weight of the aircraft",
      "The force exerted by the air on the wing"
    ],
    "correct": 1,
    "category": "Flight Mechanics"
  },
  {
    "id": 54,
    "question": "What is the effect of wind on an aircraft's True Airspeed (TAS)?",
    "options": [
      "Wind significantly changes TAS",
      "Wind has no effect on TAS, but affects Ground Speed (GS)",
      "Wind increases TAS",
      "Wind decreases TAS"
    ],
    "correct": 1,
    "category": "Flight Mechanics"
  },
  {
    "id": 55,
    "question": "What is the primary goal of the take-off phase?",
    "options": [
      "Achieving maximum altitude",
      "Accelerating the aircraft to rotation speed (V_R) and lifting off",
      "Decelerating for landing",
      "Maintaining constant velocity"
    ],
    "correct": 1,
    "category": "Flight Mechanics"
  },
  {
    "id": 56,
    "question": "If an aircraft flies from a cold area to a warm area at a constant indicated altitude, its True Altitude (TA) will:",
    "options": [
      "Decrease",
      "Increase",
      "Remain the same",
      "Be impossible to determine"
    ],
    "correct": 1,
    "category": "Flight Mechanics"
  },
  {
    "id": 57,
    "question": "What is the primary reason for banking (rolling) an aircraft during a turn?",
    "options": [
      "To increase drag",
      "To use the elevator for pitch control",
      "To align the thrust vector",
      "To tilt the lift vector horizontally to initiate the turn"
    ],
    "correct": 3,
    "category": "Flight Mechanics"
  },
  {
    "id": 58,
    "question": "The climb rate of an aircraft is dependent on the difference between the available thrust and the required:",
    "options": [
      "Lift",
      "Weight",
      "Drag",
      "Power"
    ],
    "correct": 3,
    "category": "Flight Mechanics"
  },
  {
    "id": 59,
    "question": "In a glide, the angle of the glide path is controlled by:",
    "options": [
      "Thrust setting",
      "Rudder input",
      "Elevator input to maintain airspeed",
      "Aileron input for bank angle"
    ],
    "correct": 2,
    "category": "Flight Mechanics"
  },
  {
    "id": 60,
    "question": "What is the state of the forces in a steady, unaccelerated climb?",
    "options": [
      "Thrust = Drag",
      "Lift = Weight",
      "Thrust > Drag, Lift = Weight",
      "Thrust < Drag, Lift > Weight"
    ],
    "correct": 2,
    "category": "Flight Mechanics"
  },
  {
    "id": 61,
    "question": "'Density Altitude' is pressure altitude corrected for:",
    "options": [
      "Humidity",
      "Temperature",
      "Wind speed",
      "Turbulence"
    ],
    "correct": 1,
    "category": "Flight Mechanics"
  },
  {
    "id": 62,
    "question": "The flight envelope of an aircraft is typically represented by a graph plotting which two parameters?",
    "options": [
      "Lift coefficient vs Drag coefficient",
      "Mach Number vs Altitude",
      "Velocity vs Load Factor (V-n diagram)",
      "Thrust vs Fuel flow"
    ],
    "correct": 2,
    "category": "Flight Mechanics"
  },
  {
    "id": 63,
    "question": "The term 'trimming' the aircraft refers to:",
    "options": [
      "Adjusting the position of the rudder",
      "Setting the control surfaces so the pilot feels no control force",
      "Maximizing the angle of attack",
      "Increasing engine power"
    ],
    "correct": 1,
    "category": "Flight Mechanics"
  },
  {
    "id": 64,
    "question": "What is the ground speed (GS) of an aircraft with a True Airspeed (TAS) of 200 knots flying into a 50-knot headwind?",
    "options": [
      "250 knots",
      "200 knots",
      "150 knots",
      "50 knots"
    ],
    "correct": 2,
    "category": "Flight Mechanics"
  },
  {
    "id": 65,
    "question": "What is the main characteristic of a 'longitudinal' instability?",
    "options": [
      "Tendency to diverge in a yawing motion",
      "Tendency to diverge in a rolling motion",
      "Tendency to pitch up or down and not return to equilibrium",
      "Tendency to lose engine power"
    ],
    "correct": 2,
    "category": "Flight Mechanics"
  },
  {
    "id": 66,
    "question": "What is the primary advantage of using Carbon Fiber Reinforced Polymer (CFRP) in aircraft structures over aluminum?",
    "options": [
      "Lower cost",
      "Higher density",
      "Higher strength-to-weight ratio",
      "Easier to repair"
    ],
    "correct": 2,
    "category": "Materials"
  },
  {
    "id": 67,
    "question": "What material property describes a material's resistance to permanent deformation?",
    "options": [
      "Toughness",
      "Hardness",
      "Elasticity",
      "Yield Strength"
    ],
    "correct": 3,
    "category": "Materials"
  },
  {
    "id": 68,
    "question": "What is 'Fatigue' in materials science?",
    "options": [
      "Deformation due to high heat",
      "Failure due to repeated loading/unloading cycles",
      "Immediate failure under a single heavy load",
      "Corrosion due to salt water"
    ],
    "correct": 1,
    "category": "Materials"
  },
  {
    "id": 69,
    "question": "What is 'Ductility'?",
    "options": [
      "The ability of a material to absorb energy before fracture",
      "The ability of a material to withstand a compressive load",
      "The ability of a material to be drawn out into a thin wire",
      "The ability of a material to resist abrasion"
    ],
    "correct": 2,
    "category": "Materials"
  },
  {
    "id": 70,
    "question": "Which heat-treatment process is often used to make aluminum alloys stronger?",
    "options": [
      "Annealing",
      "Tempering",
      "Solution Heat Treatment and Aging",
      "Quenching"
    ],
    "correct": 2,
    "category": "Materials"
  },
  {
    "id": 71,
    "question": "What is the main concern when joining dissimilar metals (like aluminum and steel) in an aircraft structure?",
    "options": [
      "Weight increase",
      "Galvanic Corrosion",
      "Stress concentration",
      "Fatigue limit reduction"
    ],
    "correct": 1,
    "category": "Materials"
  },
  {
    "id": 72,
    "question": "What is the modulus of elasticity (Young's Modulus)?",
    "options": [
      "Stress divided by strain in the elastic region",
      "Maximum stress a material can withstand",
      "The point at which permanent deformation begins",
      "Strain divided by stress"
    ],
    "correct": 0,
    "category": "Materials"
  },
  {
    "id": 73,
    "question": "What class of material is titanium?",
    "options": [
      "Ceramic",
      "Polymer",
      "Composite",
      "Metal Alloy"
    ],
    "correct": 3,
    "category": "Materials"
  },
  {
    "id": 74,
    "question": "What does the term 'Anisotropy' mean, particularly in composite materials?",
    "options": [
      "The material properties are the same in all directions",
      "The material is easily deformed",
      "The material properties vary with direction",
      "The material is transparent"
    ],
    "correct": 2,
    "category": "Materials"
  },
  {
    "id": 75,
    "question": "What is the name of the process where a surface material is slowly worn away by friction?",
    "options": [
      "Corrosion",
      "Erosion",
      "Torsion",
      "Creep"
    ],
    "correct": 1,
    "category": "Materials"
  },
  {
    "id": 76,
    "question": "The critical Mach number (M_crit) is the flight Mach number at which:",
    "options": [
      "The flow over the entire wing is supersonic",
      "The flow over the wing first reaches M=1.0 (local sonic speed)",
      "Shock waves are fully developed across the entire wing",
      "Maximum drag occurs"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 77,
    "question": "What does the term 'Aspect Ratio' of a wing refer to?",
    "options": [
      "Root chord / Tip chord",
      "Wingspan squared / Wing Area",
      "Max thickness / Chord",
      "Sweep angle / Taper ratio"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 78,
    "question": "Prandtl's Lifting Line Theory is used to predict which type of drag?",
    "options": [
      "Profile drag",
      "Form drag",
      "Induced drag",
      "Wave drag"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 79,
    "question": "The total drag of an aircraft is minimized when which two drag components are equal?",
    "options": [
      "Profile drag and Interference drag",
      "Parasite drag and Induced drag",
      "Skin friction drag and Form drag",
      "Wave drag and Pressure drag"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 80,
    "question": "What is the main difference between a NACA 4-digit and 5-digit airfoil series?",
    "options": [
      "The 5-digit series specifies a reflex camber for low pitching moment",
      "The 5-digit series specifies max thickness location in 5% increments",
      "The 4-digit series has a cusped trailing edge",
      "The 5-digit series is designed for supersonic flow"
    ],
    "correct": 0,
    "category": "Aerodynamics"
  },
  {
    "id": 81,
    "question": "The increase in lift coefficient (C_L) for a change in angle of attack (α) is known as the:",
    "options": [
      "Lift efficiency",
      "Lift slope (dC_L/dα)",
      "Zero-lift angle",
      "Lift divergence factor"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 82,
    "question": "For a given weight, maximum endurance flight occurs at the speed corresponding to the:",
    "options": [
      "Minimum thrust required",
      "Minimum power required",
      "Maximum available thrust",
      "Minimum drag coefficient"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 83,
    "question": "The phenomenon of 'Mach Tuck' is a result of the rearward shift of which point?",
    "options": [
      "Center of Gravity (CG)",
      "Center of Pressure (CP)",
      "Aerodynamic Center (AC)",
      "Neutral Point"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 84,
    "question": "What is the primary purpose of a vortex generator on a wing surface?",
    "options": [
      "To increase laminar flow",
      "To delay flow separation",
      "To increase overall lift coefficient",
      "To reduce parasitic drag"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 85,
    "question": "What is the definition of the Neutral Point (NP) of an aircraft?",
    "options": [
      "The point where all lift is concentrated",
      "The point where the pitching moment is zero",
      "The point about which the pitching moment is independent of C_L",
      "The point where the drag is minimum"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 86,
    "question": "What is the maximum thickness-to-chord ratio for a typical subsonic laminar flow airfoil?",
    "options": [
      "5-8%",
      "10-15%",
      "20-25%",
      "> 30%"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 87,
    "question": "When an aircraft is in a continuous dive, the force exerted on the yoke/stick due to the stick-fixed stability is primarily related to the difference between:",
    "options": [
      "Thrust and Drag",
      "Lift and Weight",
      "CG and Neutral Point",
      "Mach number and TAS"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 88,
    "question": "For a jet aircraft, maximum range typically occurs at the flight condition that maximizes the ratio:",
    "options": [
      "(L/D) · (1/V)",
      "(L/D) · V",
      "C_L/C_D",
      "C_L^(3/2)/C_D"
    ],
    "correct": 0,
    "category": "Aerodynamics"
  },
  {
    "id": 89,
    "question": "What is the term for the ratio of the speed of the fluid at a point to the local speed of sound?",
    "options": [
      "Reynolds Number",
      "Prandtl Number",
      "Mach Number",
      "Froude Number"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 90,
    "question": "What is the main effect of increasing wing sweepback on the critical Mach number?",
    "options": [
      "It decreases M_crit",
      "It increases M_crit",
      "It has no effect on M_crit",
      "It makes the flow entirely supersonic"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 91,
    "question": "What is the primary metric for comparing the efficiency of different jet engines?",
    "options": [
      "Thrust per unit weight",
      "Specific Impulse (Isp) or Specific Fuel Consumption (TSFC)",
      "Engine frontal area",
      "Compressor pressure ratio"
    ],
    "correct": 1,
    "category": "Propulsion"
  },
  {
    "id": 92,
    "question": "In an ideal turbojet engine cycle, what is the thermodynamic process that occurs in the compressor?",
    "options": [
      "Isothermal expansion",
      "Adiabatic compression",
      "Isobaric heating",
      "Isentropic compression"
    ],
    "correct": 3,
    "category": "Propulsion"
  },
  {
    "id": 93,
    "question": "What is the 'Bypass Ratio' in a turbofan engine?",
    "options": [
      "Mass flow through the core / Mass flow through the fan",
      "Mass flow through the fan / Mass flow through the core",
      "Thrust from core / Thrust from fan",
      "Total thrust / Fuel flow"
    ],
    "correct": 1,
    "category": "Propulsion"
  },
  {
    "id": 94,
    "question": "What is the main reason for using variable-area nozzles in supersonic jet engines?",
    "options": [
      "To change the bypass ratio",
      "To maintain optimal pressure ratio for both subsonic and supersonic flight",
      "To reduce noise during takeoff",
      "To cool the exhaust gas"
    ],
    "correct": 1,
    "category": "Propulsion"
  },
  {
    "id": 95,
    "question": "What is the defining characteristic of a Ramjet engine?",
    "options": [
      "It uses a compressor and turbine",
      "It has no moving parts and relies on high flight speed for compression",
      "It uses a propeller for thrust",
      "It burns liquid oxygen"
    ],
    "correct": 1,
    "category": "Propulsion"
  },
  {
    "id": 96,
    "question": "The thrust of a propeller is primarily generated by accelerating a large mass of air to a:",
    "options": [
      "High velocity",
      "Low velocity",
      "Supersonic speed",
      "Zero velocity"
    ],
    "correct": 1,
    "category": "Propulsion"
  },
  {
    "id": 97,
    "question": "What is the primary method used to prevent compressor stall (surge) in multi-stage axial compressors?",
    "options": [
      "Increasing the fuel flow",
      "Using bleed air valves or variable stator vanes",
      "Decreasing the engine RPM",
      "Changing the nozzle area"
    ],
    "correct": 1,
    "category": "Propulsion"
  },
  {
    "id": 98,
    "question": "The energy added to the airflow in the combustion chamber is related to which thermodynamic process?",
    "options": [
      "Isothermal compression",
      "Adiabatic expansion",
      "Isobaric heating",
      "Isentropic expansion"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 99,
    "question": "What is the role of the Inlet Guide Vanes (IGVs) in an axial flow compressor?",
    "options": [
      "To inject fuel",
      "To cool the blades",
      "To direct the airflow onto the first stage rotor blades at the correct angle of attack",
      "To reduce exhaust noise"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 100,
    "question": "What is the term for the maximum temperature the turbine blades can withstand?",
    "options": [
      "Stagnation temperature",
      "Turbine Entry Temperature (TET)",
      "Isentropic temperature",
      "Max ambient temperature"
    ],
    "correct": 1,
    "category": "Propulsion"
  },
  {
    "id": 101,
    "question": "What does the term 'Safe-Life' design philosophy mean for a structural component?",
    "options": [
      "It can never fail",
      "It is designed to operate safely for a specified number of cycles/hours, after which it must be replaced",
      "It is designed so that failure of one component will not cause total structural collapse",
      "It is designed for maximum strength"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 102,
    "question": "The load factor (n) experienced by an aircraft in a pull-up maneuver is defined as the ratio of:",
    "options": [
      "Lift to Drag",
      "Thrust to Weight",
      "Lift to Weight",
      "Thrust to Drag"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 103,
    "question": "What is the main purpose of a 'Rib' in a wing structure?",
    "options": [
      "To carry bending loads",
      "To carry shear loads and maintain the airfoil shape",
      "To connect the wing to the fuselage",
      "To house the landing gear"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 104,
    "question": "Which structural element primarily resists torsional (twisting) loads on the wing?",
    "options": [
      "Spars",
      "Stringers",
      "Skin (forming a closed box)",
      "Ribs"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 105,
    "question": "Which failure mode is characterized by inelastic deformation under compressive stress in thin-walled structures?",
    "options": [
      "Fracture",
      "Creep",
      "Buckling",
      "Fatigue"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 106,
    "question": "What is the primary advantage of using a semi-monocoque fuselage construction over a monocoque construction?",
    "options": [
      "Lighter weight and greater internal volume",
      "Better resistance to pressure differential",
      "Higher stiffness and easier access for internal systems",
      "Easier to manufacture"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 107,
    "question": "What is the 'Poisson's ratio' of a material?",
    "options": [
      "The ratio of stress to strain",
      "The ratio of lateral strain to axial strain",
      "The ratio of yield strength to ultimate tensile strength",
      "The ratio of volume change to original volume"
    ],
    "correct": 1,
    "category": "Materials"
  },
  {
    "id": 108,
    "question": "The material property 'Creep' refers to:",
    "options": [
      "The material's tendency to rust",
      "The material's ability to absorb shock",
      "Time-dependent inelastic deformation under a constant load at elevated temperature",
      "Failure under repeated cyclic loading"
    ],
    "correct": 2,
    "category": "Materials"
  },
  {
    "id": 109,
    "question": "What is a 'Fail-Safe' structural design approach?",
    "options": [
      "Ensuring the component never fails",
      "Designing the structure so that a single failure will not be catastrophic",
      "Designing for maximum life before replacement",
      "Using only titanium alloys"
    ],
    "correct": 1,
    "category": "Materials"
  },
  {
    "id": 110,
    "question": "What is the typical failure mechanism for a CFRP (Carbon Fiber Reinforced Polymer) laminate under excessive tensile load?",
    "options": [
      "Yielding and necking like a metal",
      "Fiber breakage and matrix cracking",
      "Buckling of the entire structure",
      "Melting"
    ],
    "correct": 1,
    "category": "Materials"
  },
  {
    "id": 111,
    "question": "What is the significance of the 7075-T6 aluminum alloy in aerospace?",
    "options": [
      "High corrosion resistance",
      "Excellent weldability",
      "High strength-to-weight ratio (used in high-stress components)",
      "Low cost and easy machining"
    ],
    "correct": 2,
    "category": "Materials"
  },
  {
    "id": 112,
    "question": "What is the yield stress of a material?",
    "options": [
      "The stress at which the material instantaneously fractures",
      "The stress required to cause plastic (permanent) deformation to begin",
      "The maximum stress before the material breaks",
      "The stress required to cause elastic deformation"
    ],
    "correct": 1,
    "category": "Materials"
  },
  {
    "id": 113,
    "question": "In a truss structure, members are primarily subject to which types of internal forces?",
    "options": [
      "Bending and Shear",
      "Tension and Compression",
      "Torsion and Bending",
      "Bending and Tension"
    ],
    "correct": 1,
    "category": "Materials"
  },
  {
    "id": 114,
    "question": "What is the purpose of using honeycomb cores in composite panels?",
    "options": [
      "To increase electrical conductivity",
      "To provide high bending stiffness with minimal weight",
      "To enhance thermal transfer",
      "To prevent electromagnetic interference"
    ],
    "correct": 1,
    "category": "Materials"
  },
  {
    "id": 115,
    "question": "What are 'Stringers' (or longitudinal stiffeners) primarily designed to resist in the fuselage?",
    "options": [
      "Hoop stress",
      "Torsion and Axial (compression/tension) loads",
      "Bending loads only",
      "Shear loads only"
    ],
    "correct": 1,
    "category": "Materials"
  },
  {
    "id": 116,
    "question": "For a 2D incompressible, potential flow over a flat plate at a small angle of attack (α), what is the magnitude of the theoretical lift coefficient (C_l) predicted by Thin Airfoil Theory?",
    "options": [
      "C_l = 2πα",
      "C_l = πα",
      "C_l = ½ρV²C_l",
      "C_l = 4πα"
    ],
    "correct": 0,
    "category": "Aerodynamics"
  },
  {
    "id": 117,
    "question": "The difference between the aerodynamic center (AC) and the center of gravity (CG) is crucial for defining which primary stability margin?",
    "options": [
      "Directional stability",
      "Lateral stability",
      "Longitudinal static margin",
      "Dynamic stability"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 118,
    "question": "The total pressure (P_0) across a normal shock wave:",
    "options": [
      "Remains constant",
      "Decreases",
      "Increases",
      "Depends only on temperature"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 119,
    "question": "What is the key assumption of the Kutta-Joukowski theorem that allows for the calculation of lift?",
    "options": [
      "The flow is viscous",
      "The flow is supersonic",
      "The flow leaves the sharp trailing edge smoothly (finite velocity)",
      "The flow is incompressible"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 120,
    "question": "What is the stability mode characterized by a heavily damped, non-oscillatory motion in pitch?",
    "options": [
      "Dutch Roll",
      "Phugoid",
      "Short Period Oscillation",
      "Spiral Mode"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 121,
    "question": "In the context of boundary layer theory, what is the significance of the Reynolds Number (Re)?",
    "options": [
      "It determines the compressibility effects of the flow",
      "It represents the ratio of inertial forces to viscous forces",
      "It determines the acoustic speed of the flow",
      "It defines the ratio of dynamic pressure to static pressure"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 122,
    "question": "What is the primary characteristic of the 'Phugoid' dynamic mode of motion?",
    "options": [
      "A high-frequency, damped oscillation in pitch",
      "A low-frequency, lightly damped oscillation in speed and altitude",
      "A high-frequency, oscillatory motion in yaw and roll",
      "An unstable divergence in speed"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 123,
    "question": "How does the lift coefficient of a finite wing (C_L,3D) relate to the lift coefficient of the 2D airfoil section (C_l,2D)?",
    "options": [
      "C_L,3D > C_l,2D at the same angle of attack",
      "C_L,3D is independent of C_l,2D",
      "C_L,3D is always lower than C_l,2D at the same angle of attack",
      "They are numerically equal"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 124,
    "question": "What is the primary control input used to initiate and control the 'Dutch Roll' mode?",
    "options": [
      "Elevator",
      "Thrust",
      "Rudder",
      "Aileron"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 125,
    "question": "What is the relationship between the Stagnation Temperature (T_0), Static Temperature (T), and Mach number (M) in an isentropic flow of a perfect gas?",
    "options": [
      "T_0/T = 1 + (γ)M²/2",
      "T_0/T = 1 + (γ-1)M²",
      "T_0/T = 1 + (γ-1)M²/2",
      "T/T_0 = (1 + (γ-1)M²/2)^γ"
    ],
    "correct": 2,
    "category": "Aerodynamics"
  },
  {
    "id": 126,
    "question": "In supersonic flight, the lift of a thin wedge airfoil is primarily generated by:",
    "options": [
      "Viscous boundary layer separation",
      "Shock waves and expansion waves",
      "Leading edge suction",
      "Induced drag"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 127,
    "question": "The 'Maneuvering Envelope' of an aircraft is bounded by the stall limit, the maximum speed limit, and the:",
    "options": [
      "Maximum available thrust",
      "Structural load limits (max positive and negative load factor)",
      "Fuel capacity limit",
      "Maximum range limit"
    ],
    "correct": 1,
    "category": "Aerodynamics"
  },
  {
    "id": 128,
    "question": "What is the thermodynamic cycle on which the ideal gas turbine engine is based?",
    "options": [
      "Otto Cycle",
      "Stirling Cycle",
      "Brayton Cycle",
      "Rankine Cycle"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 129,
    "question": "The 'Thrust Specific Fuel Consumption' (TSFC) of a jet engine is typically defined as:",
    "options": [
      "Fuel flow rate / Thrust",
      "Thrust / Fuel flow rate",
      "Fuel flow rate / Air mass flow rate",
      "Thrust / Air mass flow rate"
    ],
    "correct": 0,
    "category": "Propulsion"
  },
  {
    "id": 130,
    "question": "What is the major limitation of the 'Safe-Life' design philosophy?",
    "options": [
      "Difficulty of manufacturing",
      "It does not account for pre-existing defects or random crack initiation",
      "High weight penalty",
      "Susceptibility to environmental corrosion"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 131,
    "question": "Which concept is employed in modern large fan blades to prevent resonant vibration from causing catastrophic failure?",
    "options": [
      "Damping materials",
      "Blade tip clearance increase",
      "Blade lacing or shroud design",
      "Active noise cancellation"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 132,
    "question": "What is the primary load experienced by the skin of a pressurized fuselage?",
    "options": [
      "Bending stress",
      "Torsion",
      "Hoop stress (circumferential tension)",
      "Shear stress"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 133,
    "question": "What is the purpose of a 'Divergent-Convergent' nozzle in a turbojet engine?",
    "options": [
      "To mix the bypass air with the core flow",
      "To achieve thrust optimization at subsonic speeds",
      "It is used exclusively in subsonic engines",
      "The correct geometry for supersonic flow acceleration is a Convergent-Divergent nozzle"
    ],
    "correct": 3,
    "category": "Propulsion"
  },
  {
    "id": 134,
    "question": "The 'Design Limit Load' for an aircraft structure is typically the maximum load expected in service, multiplied by what factor to determine the 'Design Ultimate Load'?",
    "options": [
      "1.0",
      "1.25",
      "1.5",
      "2.0"
    ],
    "correct": 2,
    "category": "Structure"
  },
  {
    "id": 135,
    "question": "What is the main reason for the use of single-crystal nickel-based superalloys in modern turbine blades?",
    "options": [
      "Lower density",
      "Excellent ductility",
      "Superior resistance to high-temperature creep and fatigue",
      "Better conductivity"
    ],
    "correct": 2,
    "category": "Materials"
  },
  {
    "id": 136,
    "question": "What is the defining characteristic of a 'Scramjet' engine?",
    "options": [
      "The combustion process is subsonic",
      "It has a high bypass ratio",
      "The combustion process is supersonic",
      "It uses a propeller for thrust"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 137,
    "question": "Which structural failure criterion is generally applied to ductile materials under combined static loading?",
    "options": [
      "Maximum Principal Stress Theory",
      "Maximum Shear Stress Theory (Tresca) or Distortion Energy Theory (von Mises)",
      "Griffith's Theory",
      "Linear Elastic Fracture Mechanics"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 138,
    "question": "The 'Flutter' phenomenon in wings is an interaction between which three forces/effects?",
    "options": [
      "Thrust, Drag, and Weight",
      "Aerodynamic, Elastic, and Inertial forces",
      "Shear, Bending, and Torsion",
      "Lift, Drag, and Moment"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 139,
    "question": "What is the key advantage of a 'Geared Turbofan' engine architecture?",
    "options": [
      "Lower Turbine Entry Temperature",
      "Higher component efficiency for the core",
      "Allows the fan and the low-pressure turbine to operate at their respective optimum speeds, improving bypass ratio and TSFC",
      "Eliminates the need for a mixer nozzle"
    ],
    "correct": 2,
    "category": "Propulsion"
  },
  {
    "id": 140,
    "question": "In Fracture Mechanics, the Stress Intensity Factor (K) is used to characterize:",
    "options": [
      "The plastic deformation near a hole",
      "The stress field intensity at the tip of a crack",
      "The maximum stress in an uncracked component",
      "The fatigue life of the material"
    ],
    "correct": 1,
    "category": "Structure"
  },
  {
    "id": 141,
    "question": "The 'Breguet Range Equation' for a jet aircraft shows that range is primarily proportional to:",
    "options": [
      "(L/D) · (Fuel Weight)",
      "(L/D) · (1/TSFC) · ln(W_initial/W_final)",
      "V² · (L/D)",
      "(1/TSFC) · V_cruise"
    ],
    "correct": 1,
    "category": "Performance"
  },
  {
    "id": 142,
    "question": "What is the primary role of an 'Active Control System' (ACS) in a highly maneuverable military aircraft?",
    "options": [
      "To only control engine thrust",
      "To manage unstable aerodynamic characteristics and optimize performance",
      "To replace all mechanical controls",
      "To increase the aircraft's weight capacity"
    ],
    "correct": 1,
    "category": "Systems"
  },
  {
    "id": 143,
    "question": "What is the 'Static Stability' requirement for a flight vehicle?",
    "options": [
      "The vehicle must be able to return to its original equilibrium state immediately after a disturbance",
      "The vehicle must generate restoring forces/moments when disturbed from equilibrium",
      "The vehicle's oscillations must decay over time",
      "The vehicle must maintain a constant velocity"
    ],
    "correct": 1,
    "category": "Performance"
  },
  {
    "id": 144,
    "question": "How is the maximum rate of climb (R/C_max) for a jet aircraft determined?",
    "options": [
      "By the condition of minimum thrust required",
      "By the condition of maximum excess power ((T·V - P_required)/W)",
      "By flying at the speed of minimum drag",
      "By flying at the critical Mach number"
    ],
    "correct": 1,
    "category": "Performance"
  },
  {
    "id": 145,
    "question": "What is the core principle of a 'Fly-by-Wire' (FBW) system?",
    "options": [
      "Mechanical cables link the control column directly to the control surfaces",
      "Hydraulic fluid controls the flight surfaces only",
      "Electrical signals and computers interpret pilot input and command the control surfaces",
      "Radio waves control the aircraft"
    ],
    "correct": 2,
    "category": "Systems"
  },
  {
    "id": 146,
    "question": "The term 'Specific Energy' of an aircraft (E/W) is defined as:",
    "options": [
      "The instantaneous altitude",
      "The total energy (potential + kinetic) per unit weight",
      "The kinetic energy per unit weight",
      "The potential energy per unit weight"
    ],
    "correct": 1,
    "category": "Performance"
  },
  {
    "id": 147,
    "question": "Which navigational system relies on triangulating signals from a constellation of Earth-orbiting satellites?",
    "options": [
      "INS (Inertial Navigation System)",
      "VOR (VHF Omni-Directional Range)",
      "GPS (Global Positioning System)",
      "ADF (Automatic Direction Finder)"
    ],
    "correct": 2,
    "category": "Systems"
  },
  {
    "id": 148,
    "question": "What is the primary method of heat dissipation for high-temperature turbine blades?",
    "options": [
      "Increasing rotational speed",
      "Using high-pressure cooling air diverted from the compressor",
      "Using thick ceramic coating",
      "Decreasing fuel flow"
    ],
    "correct": 1,
    "category": "Propulsion"
  },
  {
    "id": 149,
    "question": "The 'Weight and Balance' calculation for a large aircraft is primarily concerned with ensuring the Center of Gravity (CG) remains within which limit?",
    "options": [
      "Maximum forward CG limit only",
      "Minimum aft CG limit only",
      "The entire operational envelope (forward and aft limits)",
      "The wingspan limit"
    ],
    "correct": 2,
    "category": "Performance"
  },
  {
    "id": 150,
    "question": "What is the definition of the 'Time Constant' (τ) in dynamic stability analysis?",
    "options": [
      "The time required for an oscillation to complete one cycle",
      "The time required for the disturbance amplitude to decay to 1/e (approx. 37%) of its initial value",
      "The time required to reach V_max",
      "The time required to pull maximum G-force"
    ],
    "correct": 1,
    "category": "Performance"
  }
];

// Function to get random 15 questions
export function getRandomQuestions(count: number = 15): MCQQuestion[] {
  const shuffled = [...MCQ_QUESTIONS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

// Passing criteria
export const PASSING_SCORE = 10; // 10 out of 15
export const MAX_ATTEMPTS = 3;
